package com.juno.event_data_dashboard.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import java.time.LocalDateTime;


// The User class represents a table in the database
@Entity
public class User {
    
    // This field is the primary key
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // A field is for the user's name
    private String name;

    // A field is for the user's email
    private String email;

    // Automatically set to the time of account creation
    private LocalDateTime dateCreated = LocalDateTime.now();

    // Necessary no-argument constructor for JPA to work
    public User() {}


    // Getters and setters for all fields
    // (Id has no setter since it's generated by the database)

    public Long getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public LocalDateTime getDateCreated() {
        return dateCreated;
    }

    public void setDateCreated(LocalDateTime dateCreated) {
        this.dateCreated = dateCreated;
    }

    
}
